# Mirix Configuration - Google Gemini Setup
# Configuration using Google's Gemini 2.0 Flash with large context window

llm_config:
  model: "gemini-2.0-flash"
  model_endpoint_type: "google_ai"
  model_endpoint: "https://generativelanguage.googleapis.com"
  context_window: 1000000

embedding_config:
  embedding_model: "text-embedding-004"
  embedding_endpoint_type: "google_ai"
  embedding_dim: 768

system_prompts_folder: mirix\prompts\system\base

meta_agent_config:
  agents:
    - core_memory_agent
    - resource_memory_agent
    - semantic_memory_agent
    - episodic_memory_agent
    - procedural_memory_agent
    - knowledge_vault_agent
    - meta_memory_agent
    - reflexion_agent
    - background_agent

