# Mirix Configuration - Anthropic Claude Setup
# Configuration using Anthropic's Claude 3.5 Sonnet

llm_config:
  model: "claude-3-5-sonnet-20241022"
  model_endpoint_type: "anthropic"
  model_endpoint: "https://api.anthropic.com/v1"
  context_window: 200000
  # api_key: "your-anthropic-key"  # Or use ANTHROPIC_API_KEY env var

# Note: Anthropic doesn't provide embeddings, so we use OpenAI or Google
embedding_config:
  embedding_model: "text-embedding-004"
  embedding_endpoint_type: "google_ai"
  embedding_dim: 768

meta_agent_config:
  agents:
    - core_memory_agent
    - resource_memory_agent
    - semantic_memory_agent
    - episodic_memory_agent
    - procedural_memory_agent
    - knowledge_vault_memory_agent
    - meta_memory_agent
    - reflexion_agent
    - background_agent

