# Mirix Configuration - Minimal Setup
# Minimal configuration with only essential memory agents
# Uses defaults for LLM and embeddings (gpt-4o-mini + text-embedding-004)

meta_agent_config:
  agents:
    - episodic_memory_agent    # For events and experiences
    - semantic_memory_agent     # For facts and knowledge
    - meta_memory_agent         # For coordination

