# Mirix Configuration - OpenAI Setup
# Simple configuration using OpenAI's GPT-4o-mini

llm_config:
  model: "gpt-4o-mini"
  model_endpoint_type: "openai"
  context_window: 128000

embedding_config:
  embedding_model: "text-embedding-3-small"
  embedding_endpoint_type: "openai"
  embedding_dim: 1536

meta_agent_config:
  agents:
    - core_memory_agent
    - resource_memory_agent
    - semantic_memory_agent
    - episodic_memory_agent
    - procedural_memory_agent
    - knowledge_vault_agent
    - meta_memory_agent
    - reflexion_agent
    - background_agent

